pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'nodejs-app'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Node.js and npm') {
            steps {
                script {
                    // Install npm if it's not installed
                   script {
            sh '''
                if ! npm --version >/dev/null 2>&1; then
                    sudo apt-get update
                    curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                    sudo apt-get install -y nodejs
                fi
            '''
        }
                }
            }
        }

        stage('Test Node.js') {
            steps {
                script {
                    sh 'node --version'
                    sh 'npm --version'
                }
            }
        }

        stage('Run app.js') {
            steps {
                script {
                    // Test app.js locally before Docker build
                    sh 'node app.js'
                }
            }
        }

        
}
}
