pipeline {
    agent any

    tools {
        nodejs 'nodejs' // Make sure 'nodejs' matches the name of the Node.js tool you configured in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone your repository or checkout code
                checkout scm
            }
        }

       

        stage('Build') {
            steps {
                // Build your React.js application
                sh 'npm run build'
            }
        }

    

        stage('Run Application') {
            steps {
                // Run your Node.js app
                sh 'node index.js'
            }
        }
    }

    post {
        always {
            // Cleanup node_modules after running
            sh 'rm -rf node_modules'
        }
    }
}
