pipeline {
    agent any
    environment {
        SUDO_PASSWORD = credentials('sudo-credentials')  // Replace 'sudo-credentials' with your Jenkins credential ID
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/NandhiniRavi01/devops_try', 
                                         credentialsId: 'git-credential']]  // Replace with Git credentials ID
                ])
            }
        }

       
            

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t nodejs-app .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh 'docker run -d -p 3000:3000 nodejs-app'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline complete.'
        }
    }
}
