pipeline {
    agent any

    environment {
        IMAGE_TAG = "v9"
        LOCAL_REGISTRY = "localhost:5000"
        ARGOCD_SERVER = "localhost:8081"
        ARGOCD_USER = "admin"
        ARGOCD_PASSWORD = "yHLKjwZPbFr8oamE"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'git-credential', 
                    url: 'https://github.com/NandhiniRavi01/devops_try',
                    branch: 'main'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh '''
                    echo "Building Docker Image"
                    docker build -t ${LOCAL_REGISTRY}/python-app:${IMAGE_TAG} -f sample/Dockerfile .
                    '''
                }
            }
        }

        stage('Push Docker Image to Local Registry') {
            steps {
                script {
                    sh '''
                    echo "Pushing Docker Image to Local Registry"
                    docker push ${LOCAL_REGISTRY}/python-app:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes using ArgoCD') {
            steps {
                script {
                    sh '''
                    echo "Authenticating with ArgoCD"
                    argocd login ${ARGOCD_SERVER} --username ${ARGOCD_USER} --password ${ARGOCD_PASSWORD} --insecure

                    echo "Deploying to Kubernetes"
                    argocd app sync sample
                    argocd app wait sample
                    '''
                }
            }
        }
    }
}
