pipeline {
    agent any

    environment {
        IMAGE_TAG = "latest"
        
        ARGOCD_SERVER = "localhost:8081"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'git-credential', 
                    url: 'https://github.com/NandhiniRavi01/devops_try',
                    branch: 'main'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh '''
                    echo "Building Docker Image"
                    docker build -t devopstry:${IMAGE_TAG} -f sample1/Dockerfile .
                    '''
                }
            }
        }

        stage('Cleanup Docker') {
            steps {
                script {
                    echo 'Cleaning up old Docker containers'
                    sh '''
                    docker rm -f myapp || true
                    '''
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    echo 'Running Docker Container'
                    sh '''
                    docker run -d -p 5000:5000 --name myapp devopstry:latest
                    '''
                    // Adding a wait period to ensure the container is up and running
                   
                }
            }
        }

       stage('Build') {
            steps {
                git branch: 'main', url: 'https://github.com/NandhiniRavi01/devops_try.git'
                sh 'python3 app.py'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 -m pytest'
            }
        }
    }
}
