pipeline {
    agent any

    environment {
        IMAGE_TAG = "latest"
        
        ARGOCD_SERVER = "localhost:8081"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'git-credential', 
                    url: 'https://github.com/NandhiniRavi01/devops_try',
                    branch: 'main'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh '''
                    echo "Building Docker Image"
                    docker build -t devopstry:${IMAGE_TAG} -f sample1/Dockerfile .
                    '''
                }
            }
        }

        stage('Push Docker Image to Local Registry') {
            steps {
                script {
                    sh '''
                    echo "Pushing Docker Image to Local Registry"
                    docker push devopstry:${IMAGE_TAG}
                    '''
                }
            }
        }

       stage('Build') {
            steps {
                git branch: 'main', url: 'https://github.com/NandhiniRavi01/devops_try.git'
                sh 'python3 app.py'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 -m pytest'
            }
        }
    }
}
