pipeline {
  agent {
    docker { image 'node:16-alpine' } #configure the docker
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version' #in stages it has the node js or not
      }
    }
  }
}
